---
title: "herbivore_abundances"
author: "Raine Detmer"
date: "2024-08-06"
output: html_document
---

README: code for calculating the percent abundances of herbivore species in Moorea

# packages

```{r}
library("tidyverse")
```

# read in the data

```{r}
# Package ID: knb-lter-mcr.6.62 Cataloging System:https://pasta.edirepository.org.
# Data set title: MCR LTER: Coral Reef: Long-term Population and Community Dynamics: Fishes, ongoing since 2005.
# Data set creator:    - Moorea Coral Reef LTER 
# Data set creator:  Andrew Brooks - Moorea Coral Reef LTER 
# Metadata Provider:    - Moorea Coral Reef LTER 
# Contact:    - Information Manager Moorea Coral Reef LTER  - mcrlter@msi.ucsb.edu
# Stylesheet v2.11 for metadata conversion into program: John H. Porter, Univ. Virginia, jporter@virginia.edu 

inUrl1  <- "https://pasta.lternet.edu/package/data/eml/knb-lter-mcr/6/62/ac2c7a859ce8595ec1339e8530b9ba50" 
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 dt1 <-read.csv(infile1,header=F,skip=1 ,sep="," ,quot='"' 
        , col.names=c(
                    "Year",     
                    "Date",     
                    "Start_time",     
                    "End_time",     
                    "Location",     
                    "Site",     
                    "Habitat",     
                    "Transect",     
                    "Transect_Width",     
                    "Taxonomy",     
                    "Family",     
                    "Fish_Count",     
                    "Total_Length",     
                    "Length_Anomaly",     
                    "Biomass",     
                    "Comment",     
                    "Coarse_Trophic",     
                    "Fine_Trophic",     
                    "Cloud_Cover",     
                    "Wind_Velocity",     
                    "Sea_State",     
                    "Swell",     
                    "Visibility",     
                    "Surge",     
                    "Diver"    ), check.names=TRUE)
               
unlink(infile1)
		    
# Fix any interval or ratio columns mistakenly read in as nominal and nominal columns read as numeric or dates read as strings
                                                   
# attempting to convert dt1$Date dateTime string to R date structure (date or POSIXct)                                
tmpDateFormat<-"%Y-%m-%d"
tmp1Date<-as.Date(dt1$Date,format=tmpDateFormat)
# Keep the new dates only if they all converted correctly
if(nrow(dt1[dt1$Date != "",]) == length(tmp1Date[!is.na(tmp1Date)])){dt1$Date <- tmp1Date } else {print("Date conversion failed for dt1$Date. Please inspect the data and do the date conversion yourself.")}                                                                    
                                
if (class(dt1$Start_time)!="factor") dt1$Start_time<- as.factor(dt1$Start_time)
if (class(dt1$End_time)!="factor") dt1$End_time<- as.factor(dt1$End_time)
if (class(dt1$Location)!="factor") dt1$Location<- as.factor(dt1$Location)
if (class(dt1$Site)!="factor") dt1$Site<- as.factor(dt1$Site)
if (class(dt1$Habitat)!="factor") dt1$Habitat<- as.factor(dt1$Habitat)
if (class(dt1$Transect)!="factor") dt1$Transect<- as.factor(dt1$Transect)
if (class(dt1$Transect_Width)=="factor") dt1$Transect_Width <-as.numeric(levels(dt1$Transect_Width))[as.integer(dt1$Transect_Width) ]               
if (class(dt1$Transect_Width)=="character") dt1$Transect_Width <-as.numeric(dt1$Transect_Width)
if (class(dt1$Taxonomy)!="factor") dt1$Taxonomy<- as.factor(dt1$Taxonomy)
if (class(dt1$Family)!="factor") dt1$Family<- as.factor(dt1$Family)
if (class(dt1$Fish_Count)=="factor") dt1$Fish_Count <-as.numeric(levels(dt1$Fish_Count))[as.integer(dt1$Fish_Count) ]               
if (class(dt1$Fish_Count)=="character") dt1$Fish_Count <-as.numeric(dt1$Fish_Count)
if (class(dt1$Total_Length)=="factor") dt1$Total_Length <-as.numeric(levels(dt1$Total_Length))[as.integer(dt1$Total_Length) ]               
if (class(dt1$Total_Length)=="character") dt1$Total_Length <-as.numeric(dt1$Total_Length)
if (class(dt1$Length_Anomaly)!="factor") dt1$Length_Anomaly<- as.factor(dt1$Length_Anomaly)
if (class(dt1$Biomass)=="factor") dt1$Biomass <-as.numeric(levels(dt1$Biomass))[as.integer(dt1$Biomass) ]               
if (class(dt1$Biomass)=="character") dt1$Biomass <-as.numeric(dt1$Biomass)
if (class(dt1$Comment)!="factor") dt1$Comment<- as.factor(dt1$Comment)
if (class(dt1$Coarse_Trophic)!="factor") dt1$Coarse_Trophic<- as.factor(dt1$Coarse_Trophic)
if (class(dt1$Fine_Trophic)!="factor") dt1$Fine_Trophic<- as.factor(dt1$Fine_Trophic)
if (class(dt1$Cloud_Cover)=="factor") dt1$Cloud_Cover <-as.numeric(levels(dt1$Cloud_Cover))[as.integer(dt1$Cloud_Cover) ]               
if (class(dt1$Cloud_Cover)=="character") dt1$Cloud_Cover <-as.numeric(dt1$Cloud_Cover)
if (class(dt1$Swell)=="factor") dt1$Swell <-as.numeric(levels(dt1$Swell))[as.integer(dt1$Swell) ]               
if (class(dt1$Swell)=="character") dt1$Swell <-as.numeric(dt1$Swell)
if (class(dt1$Visibility)=="factor") dt1$Visibility <-as.numeric(levels(dt1$Visibility))[as.integer(dt1$Visibility) ]               
if (class(dt1$Visibility)=="character") dt1$Visibility <-as.numeric(dt1$Visibility)
if (class(dt1$Surge)=="factor") dt1$Surge <-as.numeric(levels(dt1$Surge))[as.integer(dt1$Surge) ]               
if (class(dt1$Surge)=="character") dt1$Surge <-as.numeric(dt1$Surge)
if (class(dt1$Diver)!="factor") dt1$Diver<- as.factor(dt1$Diver)
                
# Convert Missing Values to NA for non-dates
                
dt1$Taxonomy <- as.factor(ifelse((trimws(as.character(dt1$Taxonomy))==trimws("No fish observed")),NA,as.character(dt1$Taxonomy)))
dt1$Total_Length <- ifelse((trimws(as.character(dt1$Total_Length))==trimws("-1.0")),NA,dt1$Total_Length)               
suppressWarnings(dt1$Total_Length <- ifelse(!is.na(as.numeric("-1.0")) & (trimws(as.character(dt1$Total_Length))==as.character(as.numeric("-1.0"))),NA,dt1$Total_Length))
dt1$Length_Anomaly <- as.factor(ifelse((trimws(as.character(dt1$Length_Anomaly))==trimws("na")),NA,as.character(dt1$Length_Anomaly)))
dt1$Biomass <- ifelse((trimws(as.character(dt1$Biomass))==trimws("-1")),NA,dt1$Biomass)               
suppressWarnings(dt1$Biomass <- ifelse(!is.na(as.numeric("-1")) & (trimws(as.character(dt1$Biomass))==as.character(as.numeric("-1"))),NA,dt1$Biomass))
dt1$Biomass <- ifelse((trimws(as.character(dt1$Biomass))==trimws("######.#")),NA,dt1$Biomass)               
suppressWarnings(dt1$Biomass <- ifelse(!is.na(as.numeric("######.#")) & (trimws(as.character(dt1$Biomass))==as.character(as.numeric("######.#"))),NA,dt1$Biomass))
dt1$Comment <- as.factor(ifelse((trimws(as.character(dt1$Comment))==trimws("NA")),NA,as.character(dt1$Comment)))
dt1$Coarse_Trophic <- as.factor(ifelse((trimws(as.character(dt1$Coarse_Trophic))==trimws("na")),NA,as.character(dt1$Coarse_Trophic)))
dt1$Fine_Trophic <- as.factor(ifelse((trimws(as.character(dt1$Fine_Trophic))==trimws("na")),NA,as.character(dt1$Fine_Trophic)))
dt1$Visibility <- ifelse((trimws(as.character(dt1$Visibility))==trimws("-1")),NA,dt1$Visibility)               
suppressWarnings(dt1$Visibility <- ifelse(!is.na(as.numeric("-1")) & (trimws(as.character(dt1$Visibility))==as.character(as.numeric("-1"))),NA,dt1$Visibility))

# remove intermediate steps
rm(infile1)
rm(inUrl1)
rm(tmp1Date)
rm(tmpDateFormat)

```


```{r}

#summary(dt1)

# filter the data used (up to 2022) and subset out mobile herbivores
herb <- dt1 %>% filter(Year <= "2022") %>% filter(Fine_Trophic %in% c("Excavator", "Brusher", "Browser", "Scraper", "Concealed Cropper", "Sediment Sucker", "Cropper"))  %>% mutate(Fine_Trophic = if_else(Fine_Trophic %in% c("Concealed Cropper", "Sediment Sucker", "Cropper"), "Grazer", Fine_Trophic)) # grazers = cropper, concealed_cropper, sucker

# calculate relative abundances as percent of total observations within each trophic group
herb_group <- herb %>% group_by(Habitat, Fine_Trophic, Taxonomy) %>% 
  summarize(tot_n = sum(Fish_Count, na.rm = T),
            tot_bio = sum(Biomass, na.rm = T)) %>%
  ungroup(Taxonomy) %>%
  mutate(perc_n = 100*(tot_n / sum(tot_n)),
         perc_bio = 100*(tot_bio / sum(tot_bio))) %>% ungroup() %>% 
  arrange(Habitat, Fine_Trophic, desc(perc_bio)) 

#View(herb_group)

# repeat but calculating relative abundance as percent of total herbivores
herb_tot <- herb %>% group_by(Habitat, Taxonomy) %>% 
  summarize(tot_n = sum(Fish_Count, na.rm = T),
            tot_bio = sum(Biomass, na.rm = T)) %>%
  ungroup(Taxonomy) %>%
  mutate(perc_n = 100*(tot_n / sum(tot_n)),
         perc_bio = 100*(tot_bio / sum(tot_bio))) %>% ungroup() %>% 
  arrange(Habitat, desc(perc_bio)) 


```


```{r}
# check the focal taxa
focal <- c("Scarus psittacus", "Chlorurus spilurus", "Zebrasoma scopas", "Acanthurus nigrofuscus", "Ctenochaetus striatus", "Siganus spinus", "Naso lituratus", "Naso unicornis")

herb_tot %>% filter(Taxonomy %in% focal) %>% filter(Habitat == "BA") %>% view()

herb_group %>% filter(Taxonomy %in% focal) %>% filter(Habitat == "BA") %>% view()

#herb_tot %>% filter(Taxonomy == "Acanthurus triostegus") %>% filter(Habitat == "BA") 

#herb_group %>% filter(Taxonomy == "Acanthurus triostegus") %>% filter(Habitat == "BA") 

```








